{% set name = "opentelemetry-instrumentation-sklearn" %}
{% set version = "0.44b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_sklearn-{{ version }}.tar.gz
  sha256: aa75a163ccf0c6340984915667f4603f1cd51d6705eef62a4b8c3312803af6e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.44b0
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-sklearn 
    # - scikit-learn ~=0.24.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-sklearn 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sklearn
  summary: OpenTelemetry sklearn instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
